import type { Metadata } from "next";
import { Geist_Mono, Open_Sans } from "next/font/google";
import "../globals.css";

const openSans = Open_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Track Optimizer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${openSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="container mx-auto flex flex-col justify-center min-h-screen py-8 max-w-md">
          {children}
        </main>
      </body>
    </html>
  );
}
