import type { Metadata } from "next";
import { Geist_Mono, Open_Sans } from "next/font/google";
import Header from "@/components/header";
import "../globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Track Optimizer",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${openSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        <main className="container mx-auto bg-slate-900 flex flex-col items-center justify-center min-h-screen py-12 relative">
          {children}
        </main>
      </body>
    </html>
  );
}
